@extends('front.app')

@section('content')
    <!-- Breadcrumb -->
    <div class="breadcrumb-bar">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-12 col-12">

                    <h2 class="breadcrumb-title">Mentee Rehberi</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- /Breadcrumb -->

    <!-- Page Content -->
    <div class="content">
        <div class="container-fluid">


                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="blog-view">
                            <div class="blog blog-single-post">

                                <div class="blog-content">
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><strong><span style='font-size:32px;line-height:150%;font-family:"Times New Roman",serif;color:#1F4E79;'>MENTİLER İ&Ccedil;İN</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><strong><span style='font-size:32px;line-height:150%;font-family:"Times New Roman",serif;color:#1F4E79;'>&nbsp;E-MENTORLUK PROGRAMI REHBERİ</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>&nbsp;</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>&nbsp;</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>Hazırlayanlar</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>Araştırmacı:&nbsp;</span></strong><span style='font-size:19px;font-family:"Times New Roman",serif;'>Uzm. Hem. Merve BEKE</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>İstanbul &Uuml;niversitesi Cerrahpaşa,&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Lisans&uuml;st&uuml; Eğitim Enstit&uuml;s&uuml;&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Hemşirelikte Eğitim Doktora Programı</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>Danışman:&nbsp;</span></strong><span style='font-size:19px;font-family:"Times New Roman",serif;'>Prof. Dr. H&uuml;lya KAYA</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Bezmi&acirc;lem Vakıf &Uuml;niversitesi&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Sağlık Bilimleri Fak&uuml;ltesi, Hemşirelik B&ouml;l&uuml;m&uuml;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Değerli Mentimiz,</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Bu rehber, İşe Yeni Başlayan Hemşirelere Y&ouml;nelik Geliştirilen Elektronik Mentorluk (E-mentorluk) Programı&rsquo;nın etkinliğini arttırmak, menti ve mentora işleyiş kolaylığı sunmak amacıyla hazırlanmıştır.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Rehber,</span></p>
                                    <ul style="list-style-type: disc;">
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-Mentorluk Programına ilişkin temel bilgileri</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-Mentorluk kavramı ve s&uuml;re&ccedil; tanımını</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>İdeal menti tanımını, rol ve sorumluluklarını</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Etkili bir e-mentorluk i&ccedil;in &ouml;neri ve ipu&ccedil;larını</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Programın mentiye kazanımlarını i&ccedil;erir.</span></li>
                                    </ul>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Bu s&uuml;re&ccedil;te her t&uuml;rl&uuml; soru ve &ouml;nerinizi aşağıdaki e-posta ile paylaşabilirsiniz.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-posta: gungurmerve@gmail.com</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Sevgi ve saygılarımla,</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Uzm. Hem. Merve BEKE</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>İstanbul &Uuml;niversitesi Cerrahpaşa</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Lisans&uuml;st&uuml; Eğitim Enstit&uuml;s&uuml;&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Hemşirelikte Eğitim Doktora Programı</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;color:#44546A;'>&nbsp;</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;color:#44546A;'>&nbsp;</span></strong></p>
                                    <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Calibri Light",sans-serif;color:#2E74B5;'><span style='font-family:"Times New Roman",serif;'>İ&ccedil;indekiler</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634016"><span style='font-size:21px;font-family:"Times New Roman",serif;'>Mentorluk Nedir?</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>.&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>4</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634017"><span style='font-size:21px;font-family:"Times New Roman",serif;'>Elektronik Mentorluğun (E-Mentorluk) Nedir?</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>5</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634018"><span style='font-size:21px;font-family:"Times New Roman",serif;'>E-mentorluğun Menti A&ccedil;ısından Yararları Nelerdir?</span><span style='font-size:21px;line-height: 107%;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>6</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634019"><span style='font-size:21px;font-family:"Times New Roman",serif;'>Mentinin Sahip Olması Gereken &Ouml;zellikler Nelerdir?</span><span style='font-size:21px;line-height: 107%;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>6</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634020"><span style='font-size:21px;font-family:"Times New Roman",serif;'>E-mentorluk İlişkisinde Temel Prensipler Nelerdir?</span><span style='font-size:21px;line-height: 107%;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>8</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634021"><span style='font-size:21px;font-family:"Times New Roman",serif;'>İlk G&ouml;r&uuml;şmede Dikkat Edilmesi Gerekenler</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>9</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634022"><span style='font-size:21px;font-family:"Times New Roman",serif;'>Mentiler İ&ccedil;in İlk G&ouml;r&uuml;şme İpu&ccedil;ları</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>9</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634023"><span style='font-size:21px;font-family:"Times New Roman",serif;'>E-Mentorluk G&ouml;r&uuml;şmesi Nasıl Olmalıdır?</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>10</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165634024"><span style='font-size:21px;font-family:"Times New Roman",serif;'>İlişkinin Sonlandırılmasına Dair Bilgiler</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>&nbsp;</span><span style='font-size:21px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>11</span></a></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p><span style='font-size:19px;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Mentorluk Nedir?</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentorluk; belli bir alan ya da disiplinin deneyimli olan &uuml;yesi ile o alanın yeni veya gen&ccedil; &uuml;yesi arasında, destek vermek ve gen&ccedil; olanı cesaretlendirmek i&ccedil;in g&ouml;n&uuml;ll&uuml; ya da profesyonel olarak ayrılan zaman i&ccedil;inde gelişen ve yargısız, bire bir ilişki olarak tanımlanmaktadır.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor ve mentorluk arasındaki ilişki, bir bilgi aktarımı olarak tanımlanmakta ve işbirliğine dayalı &ouml;ğrenmenin de hesaba katılması gerekmektedir. Mentorluk ilişkisinde deneyimli taraf i&ccedil;in T&uuml;rk&ccedil;e&rsquo;de yaygın olarak kabul g&ouml;rm&uuml;ş olan &ldquo;<em>mentor</em>&rdquo; s&ouml;zc&uuml;ğ&uuml; benimsenirken, bu s&uuml;recin hedef yararlanıcısı i&ccedil;in &ldquo;<em>menti</em>&rdquo; ismi kullanılmaktadır.&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Elektronik Mentorluğun (E-Mentorluk) Nedir?</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk, internet ortamında &ccedil;eşitli elektronik ya da dijital ara&ccedil;ların kullanımına dayalı bir s&uuml;re&ccedil;tir. E-mentorluk, &ldquo;<em>Kıdemli olan ile daha az deneyimli olan bireyler arasında mentorluk ilişkileri kurmak i&ccedil;in kişiye &ouml;zg&uuml;, yararlı, spesifik, eşzamanlı (senkronize), b&uuml;t&uuml;nc&uuml;l, erişilebilir ve uzun s&uuml;ren bir mentorluk desteği sağlamak i&ccedil;in internet veya elektronik aracılığıyla uygulanan yaklaşım</em>&rdquo; olarak tanımlanmaktadır.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluğun, &ldquo;<em>mentor ve mentorluk alanın forumlar, sohbet odaları, bloglar ve web- konferanslar ile birbirleriyle iletişim kurabilecekleri bilgisayar veya mobil (online) tabanlı bir iletişim yolu</em>&rdquo; olduğunu aktarmaktadır. Bu online iletişim yoluyla, mekan veya zamandan bağımsız olarak mentorluk ilişkisi geliştirebilmekte ve s&uuml;rd&uuml;rebilmektedir.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;'>E-mentorluğun Menti A&ccedil;ısından Yararları Nelerdir?</h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style="font-size:19px;line-height:107%;">&nbsp;</span></p>
                                    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;color:black;'><span style="font-size:19px;">Mentinin;&nbsp;</span></p>
                                    <ul style="list-style-type: undefined;margin-left:26px;">
                                        <li><span style="line-height:150%;font-size:19px;">G&uuml;ven duygusunu destekler. Verimliliğini ve performansını arttırır.&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Akıl y&uuml;r&uuml;tme ve karar verme becerilerini geliştirir.</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Kaygı, endişe ve hayal kırıklıklarını ifade etmesini sağlayarak, yeni fikir ve d&uuml;ş&uuml;nme yollarını bulmasını destekler.&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Sorun/olaylarla başetme becerilerini geliştirir.&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">G&ouml;rev, yetki ve sorumluluklar arasında rol ge&ccedil;işini kolaylaştırır.&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">&Ouml;ğrencilikten mesleğe ge&ccedil;işini, mesleğe uyumunu destekler, bu s&uuml;re&ccedil;te yaşanan stresi azaltır.</span></li>
                                    </ul>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style="font-size:19px;line-height:107%;">&nbsp;</span></p>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;'><span style="font-size:19px;line-height:107%;">Mentinin Sahip Olması Gereken &Ouml;zellikler Nelerdir?</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;color:black;line-height:150%;'><span style="font-size:19px;line-height:150%;">Menti;&nbsp;</span></p>
                                    <ul style="list-style-type: undefined;margin-left:26px;">
                                        <li><span style="line-height:150%;font-size:19px;">&Ouml;ğrenme ama&ccedil; ve stratejilerini geliştirebilmeli, bireysel ve mesleki &ouml;ğrenme gereksinimlerini tanımlayabilmeli,</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">&Ouml;ğrenmeye istekli, soru sormaya hevesli,&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Bireysel ve mesleki etik ilke ve değerlere uygun davranmalı,</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Kararları takip edebilmeli, sorumluluk sahibi olmalı, insiyatif almaya istekli olmalı,&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Mesleki kariyer hedefleri ve amacı olmalı,&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Analitik d&uuml;ş&uuml;nme yeteneği olmalı, eleştirileri olumlu karşılayabilmeli,&nbsp;</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">İletişim becerilerine sahip olmalı,</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Sabırlı olmalı ve mentoru ile karşılıklı g&uuml;ven ilişkisi kurmalı</span></li>
                                        <li><span style="line-height:150%;font-size:19px;">Ortak &ccedil;alışmaya a&ccedil;ık ve esnek olmalı, enerjik ve yaratıcı, yardım almaya istekli, d&uuml;r&uuml;st, sevecen, saygılı ve zeki olmalıdır&nbsp;</span></li>
                                    </ul>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;color:#1F4E79;'>E-Mentorluk Programı Temel Bilgiler</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk web sitesine (https://ementorhemsire.com/) mentor ve menti kaydınız yapılacaktır. Kayıt i&ccedil;in bilgi almak i&ccedil;in <strong>E-Mentorluk Web Sitesi Kullanım Y&ouml;nergesi&nbsp;</strong>inceleyebilirsiniz.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor-menti eşleşmeniz yapıldıktan sonra e-mentorluk programı başlamış olacak ve <strong>mentorluk s&ouml;zleşmesi&nbsp;</strong>yapılacaktır.&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor ve menti eşleştirilmesi, aynı birimde &ccedil;alışanlar arasında yapılacaktır. Aynı vardiyada &ccedil;alışmaları sağlanacak, eğer bu koşul sağlanmaz ise, e-mentorluk web sitesi bilgi kaynağı, anlık mesajlaşma kısmından menti ve mentorun iletişim kurmanız gerekmektedir. &nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Toplantılarınızı, web sitesinin size uygun olan bir zaman diliminde takvim kısmından ayarlayabileceksiniz, haftada en az bir saat toplantı yapmanız gerekmektedir.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Toplantıların devamlılığı araştırmacı tarafından kontrol edilecektir. E-mentorluk programı toplamda 4 (d&ouml;rt) hafta s&uuml;recektir.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk programı aşağıdaki doğrultuda ger&ccedil;ekleştirilecektir.</span></p>
                                    <ol style="list-style-type: decimal;">
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; Mentor ve mentinin tanışması, mentinin ve mentorun sorumluluklarının, menti-mentor ilişkisinin s&uuml;resi ve g&ouml;r&uuml;şme sıklığının, mentorluk hedeflerinin belirlenmesi.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; Mentor ve mentiler oluşturulan hedeflere ulaşmak i&ccedil;in planlama yapılması, mentilerin beklentilerini ve oldukları durumu mentorları ile paylaşması.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; Menti-mentor ilişkisinin g&ouml;zden ge&ccedil;irilmesi, uyum s&uuml;recinde yaşananlar (olumlu, olumsuz), sorunlar, bilgi ve beceri eksiklerinin g&ouml;zden ge&ccedil;irilmesi, mentinin belirlenen hedeflere ulaşıp ulaşmadığının tartışılması.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; E-mentorluk programından ortaya &ccedil;ıkan sonu&ccedil;ların değerlendirilmesi, iki tarafın karşılıklı edindiği faydaların paylaşılması, gelişim i&ccedil;in &ouml;nerilerin, mentorluk ilişkisinin sonlandırma durumunun paylaşılması ve mentorluk ilişkisinin bitirilmesi.</span></li>
                                    </ol>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><em><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor ve Mentilerin Dikkat Etmesi Gerekenler</span></em></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Gizlilik&nbsp;</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk s&uuml;recinde paylaşılan bilgiler, izin alınmadan başka kimseye aktarılamaz. Yasa ile zorunlu kılınmadık&ccedil;a, bilgiler en &uuml;st gizlilik seviyesinde korunur. Bu kural hem mentor, hem de menti i&ccedil;in ge&ccedil;erlidir.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Etik Kurallar&nbsp;</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentiye ya da &uuml;&ccedil;&uuml;nc&uuml; kişilere zarar vermemek, mentiye yarar sağlamak ve onu korumak, s&uuml;recin sınırlarını belirlemek, &ccedil;ıkar &ccedil;atışmalarını &ouml;nlemek, etik konusunda rol model olmak mentorun sorumluluğudur.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk S&uuml;resi</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk s&uuml;resi, 4 (d&ouml;rt) haftadır. Her hafta en az 1 (bir) saat g&ouml;r&uuml;şme sağlanmalıdır.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>G&ouml;r&uuml;şme Ortamı</span></strong></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Konsantrasyonun dağılmayacağı, sakin ve sade ortamlar tercih edilmelidir. G&ouml;r&uuml;şmenin b&ouml;l&uuml;nmemesine dikkat edilmelidir. Kapı kapalı, cep telefonları sessiz konumda olmalıdır. G&ouml;r&uuml;şmeler online veya telefonla yapılabilir. G&ouml;r&uuml;şme tarihleri E-mentorluk web sitesinden <strong><u>takvim</u></strong> kısmına kaydedilmelidir.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">İlk G&ouml;r&uuml;şmede Dikkat Edilmesi Gerekenler</span><span style="font-size:19px;line-height:150%;">&nbsp;</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Her ilişkinin başlangıcı &ccedil;ok &ouml;nemlidir. Bu sebeple mentorunuz/mentiniz ile ger&ccedil;ekleştireceğiniz ilk g&ouml;r&uuml;şme, ilişkinizin nasıl şekilleneceği ve s&uuml;recin nasıl ilerleyeceği konusunda belirleyici olacaktır.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-Mentorluk Programı kapsamında; mentorluk yolculuğu boyunca iletişime mentilerimizin liderlik etmesini istiyoruz. Bununla birlikte, her ilişki ortaklıkla tasarlanır ve y&uuml;r&uuml;t&uuml;l&uuml;r. Dolayısıyla hem mentor hem de mentinin ilişkinin tasarımında ve gelişiminde payı &ccedil;ok b&uuml;y&uuml;kt&uuml;r. A&ccedil;ıklık ve g&uuml;ven temelinde şekillenen bir mentorluk ilişkisi i&ccedil;in, her iki tarafın da kendisini olabildiğince a&ccedil;ık ve doğallıkla ortaya koyabilmesi &ouml;nemlidir.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>İlk g&ouml;r&uuml;şmede ele almanızı &ouml;nerdiğimiz başlıklar şu şekildedir:</span></p>
                                    <ul style="list-style-type: disc;">
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Tanışma,</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentor ve menti ilişkisinin amacının, beklentilerin belirlenmesi,</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&ouml;r&uuml;şmelerle ilgili kararların alınması (g&ouml;r&uuml;şme sıklığı, online g&ouml;r&uuml;şme platformu, tarih, saat vb.),</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>İşleyişin netleştirilmesi,</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hedeflerin belirlenmesi,</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Beklentileriniz, &ccedil;alışma tarzlarınız, rol ve sorumluluklarınız &uuml;zerine anlaşılması.</span></li>
                                    </ul>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;'><span style="font-size:19px;line-height:107%;">Mentiler İ&ccedil;in İlk G&ouml;r&uuml;şme İpu&ccedil;ları</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Aşağıdaki sorular, e-mentorluk ilişkisinin başarılı ve verimli olabilmesi i&ccedil;in &ouml;nemli bir başlangı&ccedil; noktası olacaktır.&nbsp;</span></p>
                                    <ul style="list-style-type: undefined;">
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Kendinizi nasıl tanıtırdınız?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hemşirelik kariyerinizdeki deneyimlerinizi nasıl &ouml;zetlersiniz?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&uuml;&ccedil;l&uuml; y&ouml;nleriniz nelerdir? Hangi alanlarda gelişmeye ihtiyacınız olduğunu d&uuml;ş&uuml;n&uuml;yorsunuz?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Sizin i&ccedil;in hemşirelik alanında &ouml;nemli olan şeyler nelerdir?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentorunuzla ilgili &ouml;ğrenmek istedikleriniz nelerdir?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-mentorluk s&uuml;recinden ne bekliyorsunuz?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-mentorluk ilişkisinden neler bekliyorsunuz?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-mentorluk s&uuml;recini d&uuml;ş&uuml;nd&uuml;ğ&uuml;n&uuml;zde, &ouml;n g&ouml;rd&uuml;ğ&uuml;n&uuml;z zorluklar ve fırsatlar nelerdir?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Bu yolculukta kendinizden ne bekliyorsunuz?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentorunuzdan beklentiniz nedir? Hangi davranışlar ve yaklaşımlar bu s&uuml;re&ccedil;te sizi destekler?</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>&Ouml;n&uuml;m&uuml;zdeki 1 ay i&ccedil;inde hangi hemşirelik becerilerinizi geliştirmek istiyorsunuz?</span></li>
                                    </ul>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">E-Mentorluk G&ouml;r&uuml;şmesi</span><span style="font-size:19px;line-height:150%;">&nbsp;Nasıl Olmalıdır?</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Sağlıklı bir mentorluk g&ouml;r&uuml;şmesinde aşağıdakiler bulunur:</span></p>
                                    <ul style="list-style-type: undefined;">
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Her g&ouml;r&uuml;şme, bir &ouml;nceki g&ouml;r&uuml;şmede konuşulan konular ve hedeflere bağlanır.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Her g&ouml;r&uuml;şme i&ccedil;in menti tarafından belirlenmiş bir g&uuml;ndem olur. Mentinin hazırlıklı gelmesi, &ccedil;alışmaya hız kazandırır.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentorluk s&uuml;reci i&ccedil;inde konuşulan konuların dışında kalan hen&uuml;z değinilmemiş ancak menti i&ccedil;in &ouml;nemli olan başka konulara değinilebilir.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&ouml;r&uuml;şmenin sonunda g&uuml;n&uuml;n &ouml;zeti yapılır. Neler konuştuk? Nelere değindik? Nelerin farkına vardık? Bundan sonrası i&ccedil;in neleri hedefliyoruz? &Ouml;zeti &ouml;nce mentinin, sonra mentorun yapması &ouml;nemlidir. B&ouml;ylelikle taraflar arasında netlik sağlanır, iletişim kazalarının &ouml;n&uuml;ne ge&ccedil;ilmiş olur.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Bir sonraki g&ouml;r&uuml;şme i&ccedil;in mentinin hedefinin ne olduğu konusunda karar verilir.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&ouml;r&uuml;şmeden eylem planı yaparak &ccedil;ıkılır.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Bir sonraki g&ouml;r&uuml;şme i&ccedil;in kimin ne yapacağı netleştirilir.</span></li>
                                        <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>M&uuml;mk&uuml;n ise bir sonraki g&ouml;r&uuml;şmenin zamanı ve yeri belirlenir.</span></li>
                                    </ul>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentorluk g&ouml;r&uuml;şmeleri siz mentilerin sorumluluğu altındadır. Toplanın g&uuml;ndemi, konuşulacak konu/eğitim başlıklarınız belli olmalıdır.&nbsp;</span></p>
                                    <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;'><span style="font-size:19px;line-height:107%;">İlişkinin Sonlandırılmasına Dair Bilgiler</span></h1>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk Programı 4 hafta s&uuml;rer. Normal şartlarda 4 haftalık s&uuml;re i&ccedil;erisinde mentorunuz/mentiniz ile toplamda en az 4 saatlik mentorluk g&ouml;r&uuml;şmelerini tamamladığınızda ve başlangı&ccedil;ta belirlenen hedeflere ulaşıldığında s&uuml;re&ccedil; sona erer.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Standart bir şekilde sonlandırılan s&uuml;recin sonrasında ilişkinin ve iletişimin devam edip etmeyeceği; edecekse ne şekilde ve hangi sıklıkta devam edeceği gibi konular tamamen mentor ve mentinin kararına bırakılmıştır.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Programa katılım 4 haftalık s&uuml;re boyunca en az 4 saatlik bir zaman taahh&uuml;d&uuml; gerektirir. Bununla birlikte, gerek mentorlar gerekse mentiler &ccedil;eşitli sebeplerle g&ouml;r&uuml;şmeleri sonlandırmak isteyebilirler.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Peki g&ouml;r&uuml;şmeleri hangi durumlarda sonlandırabilirsiniz ve b&ouml;yle bir durumda yapmanız gerekenler nelerdir?</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Gizlilik İlkesine Aykırı Davranış:</span></strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;Mentorluk g&ouml;r&uuml;şmelerinde gizlilik esastır. G&ouml;r&uuml;şme i&ccedil;eriği ve kişilere dair bilgiler 3. Kişilerle paylaşılmamalıdır. Gizliliğin ihlal edildiği durumlarda g&ouml;r&uuml;şmeleri sonlandırma hakkına sahipsiniz. Bu durumda gungurmerve@gmail.com &nbsp;adresinden bizimle iletişime ge&ccedil;ebilirsiniz.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Etik Dışı Davranışlar:</span></strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;Mentorluk s&uuml;re&ccedil;leri etiğe uygun y&uuml;r&uuml;t&uuml;lmesi gereken s&uuml;re&ccedil;lerdir. &Ccedil;ıkar &ccedil;atışması, uygunsuz ilişki vb. durumların yaşanması durumunda g&ouml;r&uuml;şmeleri sonlandırma hakkına sahipsiniz. B&ouml;yle bir durumda gungurmerve@gmail.com adresinden bizimle iletişime ge&ccedil;ebilirsiniz.&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Ekstra Durumlar:</span></strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;Hayatta her şey olabilir. Sağlık, iş değişikliği, ailevi sebepler vb. &ouml;n g&ouml;r&uuml;lemeyen gelişmeler ile birlikte, mentorluk s&uuml;recini devam ettiremeyeceğinizi hissedebilirsiniz.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Bu durumda; s&uuml;reci tamamlamanıza yardımcı olabilecek &ccedil;&ouml;z&uuml;m &ouml;nerileri i&ccedil;in ve/veya s&uuml;reci sonlandırmak i&ccedil;in bizden destek isteyebilirsiniz.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>B&ouml;yle bir durumda &ouml;ncelikle mentorunuzla iletişime ge&ccedil;meniz ve durumu a&ccedil;ıklıkla paylaşmanız &ouml;nemli.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:16px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><span style='font-size:21px;line-height:150%;font-family:"Times New Roman",serif;color:#374151;background:#F7F7F8;'>Bu değerli mentorluk yolculuğunda bizimle birlikte olduğunuz i&ccedil;in teşekk&uuml;r ederiz.</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                </div>
                            </div>

                        </div>
                    </div>



                </div>

        </div>

    </div>
    <!-- /Page Content -->
@endsection
