@extends('front.app')

@section('content')
    <!-- Breadcrumb -->
    <div class="breadcrumb-bar">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-12 col-12">

                    <h2 class="breadcrumb-title">Mentee Rehberi</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- /Breadcrumb -->

    <!-- Page Content -->
    <div class="content">
        <div class="container-fluid">


            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="blog-view">
                        <div class="blog blog-single-post">

                            <div class="blog-content">
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;color:#1F4E79;'>&nbsp;</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><strong><span style='font-size:32px;line-height:150%;font-family:"Times New Roman",serif;color:#1F4E79;'>MENTORLAR İ&Ccedil;İN</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><strong><span style='font-size:32px;line-height:150%;font-family:"Times New Roman",serif;color:#1F4E79;'>&nbsp;E-MENTORLUK PROGRAMI REHBERİ</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>Hazırlayanlar</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>Araştırmacı:&nbsp;</span></strong><span style='font-size:19px;font-family:"Times New Roman",serif;'>Uzm. Hem. Merve BEKE</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>İstanbul &Uuml;niversitesi Cerrahpaşa,&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Lisans&uuml;st&uuml; Eğitim Enstit&uuml;s&uuml;&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Hemşirelikte Eğitim Doktora Programı</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><strong><span style='font-size:19px;font-family:"Times New Roman",serif;color:#44546A;'>Danışman:&nbsp;</span></strong><span style='font-size:19px;font-family:"Times New Roman",serif;'>Prof. Dr. H&uuml;lya KAYA</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Bezmi&acirc;lem Vakıf &Uuml;niversitesi&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:19px;font-family:"Times New Roman",serif;'>Sağlık Bilimleri Fak&uuml;ltesi, Hemşirelik B&ouml;l&uuml;m&uuml;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Değerli Mentorumuz,</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Bu rehber, İşe Yeni Başlayan Hemşirelere Y&ouml;nelik Geliştirilen Elektronik Mentorluk (E-mentorluk) Programı&rsquo;nın etkinliğini arttırmak, menti ve mentora işleyiş kolaylığı sunmak amacıyla hazırlanmıştır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Rehberde,</span></p>
                                <ul style="list-style-type: disc;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-Mentorluk Programına ilişkin temel bilgiler</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-Mentorluk kavramı ve s&uuml;reci</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Menti ve mentor tanımı, rol ve sorumlulukları</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Etkili bir e-mentorluk i&ccedil;in &ouml;neri ve ipu&ccedil;ları</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Programın mentor a&ccedil;ısından yararları yer almaktadır.</span></li>
                                </ul>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Bu rehber, sizlerin mentorluk s&uuml;recinde değerli deneyimleriniz ile mentiye rehberlik etmenizi kolaylaştırmayı ama&ccedil;lamaktadır. Bu s&uuml;re&ccedil;te her t&uuml;rl&uuml; soru ve &ouml;nerinizi aşağıdaki e-posta ile paylaşabilirsiniz.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-posta: gungurmerve@gmail.com</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Sevgi ve saygılarımla,</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Uzm. Hem. Merve BEKE</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>İstanbul &Uuml;niversitesi Cerrahpaşa,&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Lisans&uuml;st&uuml; Eğitim Enstit&uuml;s&uuml;&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Hemşirelikte Eğitim Doktora Programı</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:normal;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;&Ouml;ğrencisi</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;color:#44546A;'>&nbsp;</span></strong></p>
                                <p style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Calibri Light",sans-serif;color:#2E74B5;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>İ&ccedil;indekiler</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p><br></p>
                                <p>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885201"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Mentorluk Nedir?</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>4</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885202"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Elektronik Mentorluk (E-Mentorluk) Nedir?</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>5</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885203"><span style='font-size:19px;font-family:"Times New Roman",serif;'>E-mentorluğun Mentor A&ccedil;ısından Yararları Nelerdir?</span><span style='font-size:19px;line-height: 107%;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>6</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885204"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Mentorun Sahip Olması Gereken &Ouml;zellikler Nelerdir?</span><span style='font-size:19px;line-height: 107%;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>6</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885205"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Mentorun Rol ve Sorumlulukları Nelerdir?</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>7</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885206"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Mentorluk İlişkisinde Temel İlkeler Nelerdir?</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>8</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885207"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Mentorluk İlişkisinde Temel Prensipler Nelerdir?</span><span style='font-size:19px;line-height: 107%;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>9</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885208"><span style='font-size:19px;font-family:"Times New Roman",serif;'>İlk G&ouml;r&uuml;şmede Dikkat Edilmesi Gerekenler</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>10</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885209"><span style='font-size:19px;font-family:"Times New Roman",serif;'>E-Mentorluk G&ouml;r&uuml;şmesi Nasıl Olmalıdır?</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>.&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>11</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885210"><span style='font-size:19px;font-family:"Times New Roman",serif;'>Mentorlar i&ccedil;in İlk G&ouml;r&uuml;şme İpu&ccedil;ları</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>11</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:5.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="#_Toc165885211"><span style='font-size:19px;font-family:"Times New Roman",serif;'>İlişkinin Sonlandırılmasına Dair Temel Bilgiler</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration:none;'>&nbsp;</span><span style='font-size:19px;font-family:"Times New Roman",serif;color:windowtext;text-decoration: none;'>12</span></a></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><strong><span style='font-size:21px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:right;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p><span style='font-size:19px;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Mentorluk Nedir?</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentorluk; belli bir alan ya da disiplinin deneyimli olan &uuml;yesi ile o alanın yeni veya gen&ccedil; &uuml;yesi arasında, destek vermek ve gen&ccedil; olanı cesaretlendirmek i&ccedil;in g&ouml;n&uuml;ll&uuml; ya da profesyonel olarak ayrılan zaman i&ccedil;inde gelişen ve yargısız, bire bir ilişki olarak tanımlanmaktadır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor ve mentorluk arasındaki ilişki, bir bilgi aktarımı olarak tanımlanmakta ve işbirliğine dayalı &ouml;ğrenmenin de hesaba katılması gerekmektedir. Mentorluk ilişkisinde deneyimli taraf i&ccedil;in T&uuml;rk&ccedil;e&rsquo;de yaygın olarak kabul g&ouml;rm&uuml;ş olan &ldquo;<em>mentor</em>&rdquo; s&ouml;zc&uuml;ğ&uuml; benimsenirken, bu s&uuml;recin hedef yararlanıcısı i&ccedil;in &ldquo;<em>menti</em>&rdquo; ismi kullanılmaktadır.&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Elektronik Mentorluk (E-Mentorluk) Nedir?</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E- mentorluk, internet ortamında &ccedil;eşitli elektronik ya da dijital ara&ccedil;ların kullanımına dayalı bir s&uuml;re&ccedil;tir. E-mentorluk, &ldquo;<em>Kıdemli olan ile daha az deneyimli olan bireyler arasında mentorluk ilişkileri kurmak i&ccedil;in kişiye &ouml;zg&uuml;, yararlı, spesifik, eşzamanlı (senkronize), b&uuml;t&uuml;nc&uuml;l, erişilebilir ve uzun s&uuml;ren bir mentorluk desteği sağlamak i&ccedil;in internet veya elektronik aracılığıyla uygulanan yaklaşım</em>&rdquo; olarak tanımlanmaktadır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluğun, &ldquo;<em>mentor ve mentorluk alanın forumlar, sohbet odaları, bloglar ve web- konferanslar ile birbirleriyle iletişim kurabilecekleri bilgisayar veya mobil (online) tabanlı bir iletişim yolu</em>&rdquo; olduğunu aktarmaktadır. Bu online iletişim yoluyla, mekan veya zamandan bağımsız olarak mentorluk ilişkisi geliştirebilmekte ve s&uuml;rd&uuml;rebilmektedir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><br></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">&nbsp;</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">E-mentorluğun Mentor A&ccedil;ısından Yararları Nelerdir?</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluğun mentorlara faydaları;&nbsp;</span></p>
                                <ul style="list-style-type: undefined;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Farklı bakış a&ccedil;ısıyla olayları/durumları değerlendirmesini sağlamaktadır.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Daha &ouml;nceden net g&ouml;remediği konularla/olaylarla ilgili farkındalık kazanmasını sağlamaktadır.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Empati ve iletişim becerilerini geliştirmektedir.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin bireysel ve mesleki gelişimine katkıda bulunarak manevi doyum yaşamasına ve &ouml;zg&uuml;veninin artmasına neden olmaktadır.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Stresle baş etme becerilerini geliştirerek, onların gelişimini engelleyen durumlarla başa &ccedil;ıkmalarına yardımcı olmaktadır.</span></li>
                                </ul>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Mentorun Sahip Olması Gereken &Ouml;zellikler Nelerdir?</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk s&uuml;recinin etkili ve verimli olarak s&uuml;rd&uuml;r&uuml;lebilmesi i&ccedil;in s&uuml;recin en &ouml;nemli &ouml;ğelerinden biri olan mentorun sahip olması gereken &ouml;zellikler şu şekilde sıralanabilir;&nbsp;</span></p>
                                <ul style="list-style-type: undefined;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Etkili iletişim becerilerine sahip olma, iyi bir dinleyici olma,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&ouml;n&uuml;ll&uuml;l&uuml;k ve istekliliğini ilişkiye yansıtabilme,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Teşvik edici, cesaretlendirici ve g&uuml;&ccedil;lendirici, enerjik yaklaşımlar sergileme,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>&Ccedil;&ouml;z&uuml;m odaklı olma, mentisini kendi &ccedil;&ouml;z&uuml;mlerini bulmaya y&ouml;nlendirme,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Sakin, sabırlı ve esnek olabilme,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Kendine g&uuml;ven ve farkındalık sahibi olma,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Bireysel farklılıklara karşı saygılı ve hoşg&ouml;r&uuml;l&uuml; olma,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>&Ouml;ğrenme ve gelişime a&ccedil;ık olma,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>İlişki y&ouml;netimi becerileri sergileyebilme,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin gelişim potansiyeline, akademik durumuna, hedeflerine ve kişisel ihtiya&ccedil;larına saygılı olmak.</span></li>
                                </ul>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Mentorun Rol ve Sorumlulukları Nelerdir?</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman",serif;'>İyi bir e-mentorluk s&uuml;reci i&ccedil;in mentor rol ve sorumluluklarının farkında olmalı. Bu rol ve sorumluklar;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor;</span></p>
                                <ul style="list-style-type: undefined;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Kendi rol ve sorumluluklarını bilmeli, alanında uzman olmalı, mesleki bilgi, beceri, tutum ve deneyime sahip olmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Menti ile bilgi, beceri ve deneyimlerini paylaşmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin bilgi, beceri ve tutumunu geliştirebilmesi i&ccedil;in destek vermeye istekli olmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Karşılaşılan sorunlara profesyonel &ccedil;&ouml;z&uuml;mler &uuml;retebilmeli,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin her zaman rahat erişebileceği ve her konuda danışabileceği şekilde ulaşılabilir olmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>İyi iletişim becerilerine sahip olmalı, s&ouml;zl&uuml;, yazılı ve s&ouml;zel olmayan mesajları yorumlayabilmeli,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Online ortamda mentiye vereceği eğitimi &ouml;nceden planlamalı, eğitim d&ouml;k&uuml;manlarını hazırlamalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Ger&ccedil;ekleştirilen mentor-menti toplantısının ardından kazanımları (ama&ccedil;-hedefler) menti tartışarak değerlendirmeli, yapıcı geri bildirim vermeli,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Toplantı değerlendirme s&uuml;recinde de akıl y&uuml;r&uuml;tme ve beyin fırtınası vb. Y&ouml;ntemleri kullanmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin ama&ccedil;larını, gereksinimlerini ve gelecek planlarını paylaşarak d&uuml;r&uuml;st, duyarlı ve a&ccedil;ık bir iletişimin kullanıldığı &ccedil;alışma ve eğitim ortamı oluşturmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin performansını g&ouml;zden ge&ccedil;irerek onun g&uuml;&ccedil;l&uuml; ve geliştirilmesi gereken y&ouml;nlerini değerlendirmeli, fırsat ve tehditler konusunda &ouml;neriler getirmeli, psikolojik olarak destek olmalı ve onları motive etmeli</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentiyi yalnızca mesleki beceri kazanması a&ccedil;ısından değil, eleştirel d&uuml;ş&uuml;nme, sorun &ccedil;&ouml;zme becerisi geliştirme, yenilikleri izleme, yaratıcılığını ortaya koyma vb. konularda desteklemeli,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentiyi iş doyumu ve &ouml;zg&uuml;ven gelişimi konularında desteklemeli, karar verme konusunda model olmalı,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentinin bağımsız performans g&ouml;stermeye hazır olduğu halde uygulama yapma konusunda isteksiz olması durumunda bilgi ve becerilerini geliştirmesine, &ouml;zg&uuml;ven gelişimine yardımcı olmalı ve onu desteklemeli,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Sabırlı, ilgili, bilgili, istekli, samimi, adil, saygılı, a&ccedil;ık fikirli olmalıdır</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentiye &ccedil;alışma ortamının g&uuml;nl&uuml;k rutin işlerini ve işleyişi g&ouml;stermek, prosed&uuml;r-talimat ve raporlama sistemlerini a&ccedil;ıklamalı</span></li>
                                </ul>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;'>&nbsp;Mentorluk İlişkisinde Temel İlkeler Nelerdir?</h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk web sitesine (https://ementorhemsire.com/) ilişkin <strong>E-Mentorluk Kullanım Kılavuzunu&nbsp;</strong>inceleyebilirsiniz. Sisteme giriş yapabilmeniz i&ccedil;in sistem y&ouml;neticisi tarafından kaydınız yapılacaktır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk programına başlamadan &ouml;nce <strong>mentorluk s&ouml;zleşmesini&nbsp;</strong>onaylamanız gerekmektedir.<strong>&nbsp;</strong>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor ve menti eşleştirilmesi, aynı birimde &ccedil;alışanlar arasında yapılacaktır. Aynı vardiyada &ccedil;alışmaları sağlanacak, eğer bu koşul sağlanmaz ise, e-mentorluk web sitesi bilgi kaynağı, anlık mesajlaşma kısmından menti ve mentorun iletişim kurmanız gerekmektedir. &nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Toplantılarınızı, web sitesinin size uygun olan bir zaman diliminde takvim kısmından ayarlayabileceksiniz, haftada en az bir saat toplantı yapmanız beklenmektedir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Toplantıların devamlılığı sistem y&ouml;neticisi &nbsp;tarafından izlenecektir. E-mentorluk programının toplam 4 (d&ouml;rt) hafta s&uuml;rmesi hedeflenmiştir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk s&uuml;reci aşağıdaki doğrultuda ger&ccedil;ekleştirilecektir.</span></p>
                                <ol style="list-style-type: decimal;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; Mentor ve mentinin tanışması, mentinin ve mentorun sorumluluklarının, menti-mentor ilişkisinin s&uuml;resi ve g&ouml;r&uuml;şme sıklığının, mentorluk hedeflerinin belirlenmesi.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; Mentor ve mentiler oluşturulan hedeflere ulaşmak i&ccedil;in planlama yapılması, mentilerin beklentilerini ve oldukları durumu mentorları ile paylaşması.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; Menti-mentor ilişkisinin g&ouml;zden ge&ccedil;irilmesi, uyum s&uuml;recinde yaşananlar (olumlu, olumsuz), sorunlar, bilgi ve beceri eksiklerinin g&ouml;zden ge&ccedil;irilmesi, mentinin belirlenen hedeflere ulaşıp ulaşmadığının tartışılması.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hafta; E-mentorluk programından ortaya &ccedil;ıkan sonu&ccedil;ların değerlendirilmesi, iki tarafın karşılıklı edindiği faydaların paylaşılması, gelişim i&ccedil;in &ouml;nerilerin, mentorluk ilişkisinin sonlandırma durumunun paylaşılması ve mentorluk ilişkisinin bitirilmesi.</span></li>
                                </ol>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><em><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentor ve Mentilerin Dikkat Etmesi Gerekenler</span></em></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Gizlilik&nbsp;</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentorluk s&uuml;recinde paylaşılan bilgiler, izin alınmadan başka kimseye aktarılamaz. Yasa ile zorunlu kılınmadık&ccedil;a, bilgiler en &uuml;st gizlilik seviyesinde korunur. Bu kural hem mentor, hem de menti i&ccedil;in ge&ccedil;erlidir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Etik Kurallar&nbsp;</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentiye ya da &uuml;&ccedil;&uuml;nc&uuml; kişilere zarar vermemek, mentiye yarar sağlamak ve onu korumak, s&uuml;recin sınırlarını belirlemek, &ccedil;ıkar &ccedil;atışmalarını &ouml;nlemek, etik konusunda rol model olmak mentorun sorumluluğudur.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentorluk S&uuml;resi</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Mentorluk s&uuml;resi, 4 (d&ouml;rt) haftadır. Her hafta en az 1 (bir) saat g&ouml;r&uuml;şme sağlanmalıdır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>G&ouml;r&uuml;şme Ortamı</span></strong></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Konsantrasyonun dağılmayacağı, sakin ve sade ortamlar tercih edilmelidir. G&ouml;r&uuml;şmenin b&ouml;l&uuml;nmemesine dikkat edilmelidir. Kapı kapalı, cep telefonları sessiz konumda olmalıdır. G&ouml;r&uuml;şmeler online veya telefonla yapılabilir. G&ouml;r&uuml;şme tarihleri E-mentorluk web sitesinden <strong><u>takvim</u></strong> kısmına kaydedilmelidir.</span></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">İlk G&ouml;r&uuml;şmede Dikkat Edilmesi Gerekenler</span><span style="font-size:19px;line-height:150%;">&nbsp;</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Her ilişkinin başlangıcı &ccedil;ok &ouml;nemlidir. Bu sebeple mentiniz ile ger&ccedil;ekleştireceğiniz ilk g&ouml;r&uuml;şme, ilişkinizin nasıl şekilleneceği ve s&uuml;recin nasıl ilerleyeceği konusunda belirleyici olacaktır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-Mentorluk Programı kapsamında; her ilişki ortak kararlarla tasarlanıp ve y&uuml;r&uuml;t&uuml;lmelidir. Hem mentor hem de mentinin ilişkinin tasarımında ve gelişiminde payı &ccedil;ok b&uuml;y&uuml;kt&uuml;r. A&ccedil;ıklık ve g&uuml;ven temelinde şekillenen bir mentorluk ilişkisi i&ccedil;in, her iki tarafın da kendisini olabildiğince a&ccedil;ık ve doğallıkla ortaya koyabilmesi &ouml;nemlidir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>İlk g&ouml;r&uuml;şmede ele almanızı &ouml;nerdiğimiz başlıklar şu şekildedir:</span></p>
                                <ul style="list-style-type: disc;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Tanışma,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Mentor ve menti ilişkisinin amacının, beklentilerin belirlenmesi,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&ouml;r&uuml;şmelerle ilgili kararların alınması (g&ouml;r&uuml;şme sıklığı, online g&ouml;r&uuml;şme platformu, tarih, saat vb.),</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>İşleyişin netleştirilmesi,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hedeflerin belirlenmesi,</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Beklentiler, &ccedil;alışma tarzları, rol ve sorumluluklar &uuml;zerine anlaşmaya varılması.</span></li>
                                </ul>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">E-Mentorluk G&ouml;r&uuml;şmesi</span><span style="font-size:19px;line-height:150%;">&nbsp;Nasıl Olmalıdır?</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Sağlıklı bir ementorluk g&ouml;r&uuml;şmesinde aşağıdakiler bulunur:</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; Her g&ouml;r&uuml;şme, bir &ouml;nceki g&ouml;r&uuml;şmede konuşulan konular ve hedeflere bağlanır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; Her g&ouml;r&uuml;şme i&ccedil;in menti tarafından belirlenmiş bir g&uuml;ndem olur. Mentinin hazırlıklı gelmesi, &ccedil;alışmaya hız kazandırır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; E-mentorluk s&uuml;reci i&ccedil;inde konuşulan konuların dışında kalan hen&uuml;z değinilmemiş ancak menti i&ccedil;in &ouml;nemli olan başka konulara değinilebilir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; G&ouml;r&uuml;şmenin sonunda g&uuml;n&uuml;n &ouml;zeti yapılır. Neler konuştuk? Nelere değindik? Nelerin farkına vardık? Bundan sonrası i&ccedil;in neleri hedefliyoruz? &Ouml;zeti &ouml;nce mentinin, sonra mentorun yapması &ouml;nemlidir. B&ouml;ylelikle taraflar arasında netlik sağlanır, iletişim kazalarının &ouml;n&uuml;ne ge&ccedil;ilmiş olur.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; Bir sonraki g&ouml;r&uuml;şme i&ccedil;in mentinin hedefinin ne olduğu konusunda karar verilir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; G&ouml;r&uuml;şmeden eylem planı yaparak &ccedil;ıkılır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; Bir sonraki g&ouml;r&uuml;şme i&ccedil;in kimin ne yapacağı netleştirilir.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&bull; M&uuml;mk&uuml;n ise bir sonraki g&ouml;r&uuml;şmenin zamanı ve yeri belirlenir.</span></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;line-height:150%;'><span style="font-size:19px;line-height:150%;">Mentorlar i&ccedil;in İlk G&ouml;r&uuml;şme İpu&ccedil;ları</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>İlk g&ouml;r&uuml;şme &ouml;ncesinde aşağıdaki konular &uuml;zerinde d&uuml;ş&uuml;nmeniz yararlı olur:</span></p>
                                <ul style="list-style-type: disc;">
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Kendinizi nasıl tanıtacağınıza y&ouml;nelik hazırlık yapın.&nbsp;</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-mentorluk ilişkisinde sizin i&ccedil;in temel prensiplerin neler olduğunu d&uuml;ş&uuml;n&uuml;n.&nbsp;</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>E-mentorluk s&uuml;recinde size nasıl bir anlam kattığınızı d&uuml;ş&uuml;n&uuml;n.&nbsp;</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Ortak y&ouml;nlerinizi ve farklılaşan y&ouml;nlerinizi belirleyin. Bu konuşmalar ilişkinin başlaması ve g&uuml;&ccedil;lenmesine yardımcı olur.&nbsp;</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Hemşirelik alanında hangi konularda deneyim paylaşımı yapabileceğinizi ve katkı sağlayabileceğinizi d&uuml;ş&uuml;n&uuml;n.&nbsp;</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>G&ouml;r&uuml;şmelere hazırlıklı gelmek ve iletişime liderlik etmek, mentilerinizin sorumluluğundadır.</span></li>
                                    <li><span style='line-height:150%;font-family:"Times New Roman",serif;font-size:19px;'>Eğer mentinin zorlandığını ya da tıkandığını hissederseniz, aşağıda paylaştığımız <strong>ilk g&ouml;r&uuml;şme ipu&ccedil;ları</strong> b&ouml;l&uuml;m&uuml;ne g&ouml;z atarak sohbetinizi ilerletebilir ve derinleştirebilirsiniz.</span></li>
                                </ul>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:21px;font-family:"Times New Roman",serif;color:#1F4E79;'><span style="font-size:19px;line-height:107%;">İlişkinin Sonlandırılmasına Dair Temel Bilgiler</span></h1>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>E-mentorluk Programı 4 hafta s&uuml;recektir. Normal şartlarda 4 haftalık s&uuml;re i&ccedil;erisinde mentiniz ile toplamda en az 4 saatlik mentorluk g&ouml;r&uuml;şmelerini tamamladığınızda ve başlangı&ccedil;ta belirlenen hedeflere ulaşıldığında s&uuml;re&ccedil; sona erer.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Standart bir şekilde sonlandırılan s&uuml;recin sonrasında ilişkinin ve iletişimin devam edip etmeyeceği; edecekse ne şekilde ve hangi sıklıkta devam edeceği gibi konular tamamen mentor ve mentinin kararına bırakılır.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Programa katılım 4 haftalık s&uuml;re boyunca en az 4 saatlik bir zaman gerektirir. Bununla birlikte, gerek mentorlar gerekse mentiler &ccedil;eşitli sebeplerle g&ouml;r&uuml;şmeleri sonlandırmak isteyebilirler.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Peki g&ouml;r&uuml;şmeleri hangi durumlarda sonlandırabilirsiniz ve b&ouml;yle bir durumda yapmanız gerekenler nelerdir?</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Gizlilik İlkesine Aykırı Davranış:</span></strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;Mentorluk g&ouml;r&uuml;şmelerinde gizlilik esastır. G&ouml;r&uuml;şme i&ccedil;eriği ve kişilere dair bilgiler 3. Kişilerle paylaşılmamalıdır. Gizliliğin ihlal edildiği durumlarda g&ouml;r&uuml;şmeleri sonlandırma hakkına sahipsiniz. Bu durumda gungurmerve@gmail.com &nbsp;adresinden bizimle iletişime ge&ccedil;ebilirsiniz.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Etik Dışı Davranışlar:</span></strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;Mentorluk s&uuml;re&ccedil;leri etiğe uygun y&uuml;r&uuml;t&uuml;lmesi gereken s&uuml;re&ccedil;lerdir. &Ccedil;ıkar &ccedil;atışması, uygunsuz ilişki vb. durumların yaşanması durumunda g&ouml;r&uuml;şmeleri sonlandırma hakkına sahipsiniz. B&ouml;yle bir durumda gungurmerve@gmail.com adresinden bizimle iletişime ge&ccedil;ebilirsiniz.&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Ekstra Durumlar:</span></strong><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;Hayatta her şey olabilir. Sağlık, iş değişikliği, ailevi sebepler vb. &ouml;n g&ouml;r&uuml;lemeyen gelişmeler ile birlikte, mentorluk s&uuml;recini devam ettiremeyeceğinizi hissedebilirsiniz.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>Bu durumda; s&uuml;reci tamamlamanıza yardımcı olabilecek &ccedil;&ouml;z&uuml;m &ouml;nerileri i&ccedil;in ve/veya s&uuml;reci sonlandırmak i&ccedil;in bizden destek isteyebilirsiniz.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>B&ouml;yle bir durumda &ouml;ncelikle mentinizle iletişime ge&ccedil;meniz ve durumu a&ccedil;ıklıkla paylaşmanız &ouml;nemli.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><br></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:center;line-height:150%;'><span style='font-size:21px;line-height:150%;font-family:"Times New Roman",serif;color:#374151;background:#F7F7F8;'>Bu değerli mentorluk yolculuğunda bizimle birlikte olduğunuz i&ccedil;in teşekk&uuml;r ederiz.</span></p>
                                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri",sans-serif;text-align:justify;line-height:150%;'><span style='font-size:19px;line-height:150%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                            </div>
                        </div>

                    </div>
                </div>



            </div>

        </div>

    </div>
    <!-- /Page Content -->
@endsection
